include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=feature-based-molecular-networking
TOOL_FOLDER_NAME=feature-based-molecular-networking
WORKFLOW_VERSION=release_14
WORKFLOW_DESCRIPTION='Feature-Based Molecular Networking (FBMN) is a computational method that bridges popular mass spectrometry data processing tools for LC-MS/MS and molecular networking analysis on GNPS. The supported tools are: MZmine, OpenMS, MS-DIAL, MetaboScape, XCMS, Progenesis QI, and the mzTab-M format. See the documentation at <a href>"https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/">https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/</a> and our bioarXiv preprint at <a href="https://www.biorxiv.org/content/10.1101/812404v1">https://www.biorxiv.org/content/10.1101/812404v1</a>.'
